_G.PlayerFrame.PlayerFrameContent.PlayerFrameContentMain.ManaBarArea.ManaBar.FeedbackFrame:Hide()
_G.PlayerFrame.PlayerFrameContent.PlayerFrameContentMain.ManaBarArea.ManaBar.FullPowerFrame:Hide()
_G.PlayerFrame:UnregisterEvent("UNIT_COMBAT")

-- Disable action bar casts
_G.ActionBarActionEventsFrame:UnregisterEvent("UNIT_SPELLCAST_SUCCEEDED")
_G.ActionBarActionEventsFrame:UnregisterEvent("UNIT_SPELLCAST_INTERRUPTED")
_G.ActionBarActionEventsFrame:UnregisterEvent("UNIT_SPELLCAST_FAILED")
_G.ActionBarActionEventsFrame:UnregisterEvent("UNIT_SPELLCAST_START")
_G.ActionBarActionEventsFrame:UnregisterEvent("UNIT_SPELLCAST_STOP")
_G.ActionBarActionEventsFrame:UnregisterEvent("UNIT_SPELLCAST_CHANNEL_START")
_G.ActionBarActionEventsFrame:UnregisterEvent("UNIT_SPELLCAST_CHANNEL_STOP")
_G.ActionBarActionEventsFrame:UnregisterEvent("UNIT_SPELLCAST_RETICLE_TARGET")
_G.ActionBarActionEventsFrame:UnregisterEvent("UNIT_SPELLCAST_RETICLE_CLEAR")
_G.ActionBarActionEventsFrame:UnregisterEvent("UNIT_SPELLCAST_EMPOWER_START")
_G.ActionBarActionEventsFrame:UnregisterEvent("UNIT_SPELLCAST_EMPOWER_STOP")
